development:
  adapter: postgresql
  encoding: utf8
  database: salon_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  database: salon_test
  pool: 5

production:
  adapter: postgresql
  database: salon_production
  pool: 5
  timeout: 5000
