development:
  adapter: postgresql
  encoding: utf8
  database: salon_development
  pool: 5
  username: salon_user
  password: secretpassword

test:
  adapter: postgresql
  encoding: utf8
  database: salon_test
  pool: 5
  username: salon_user
  password: secretpassword

production:
  adapter: postgresql
  database: kava_database
  pool: 5
  timeout: 5000
